# This is a basic workflow to help you get started with Actions

name: github_actions_practice

run-name: ${{ github.actor }} is trying to run a truncated CI/CD workflow

# Controls when the workflow will run
on:
  # Triggers the workflow for any pushes made to any branch
  push:

  # Allows for the workflow to run manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow will need two jobs - one for the rest and one for the test
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t test-image -f src/test_Dockerfile .

      - name: Run the tests
        run: docker run -e URL=http://127.0.0.1:5000 test-image python test.py
